### ISSUE TITLE
Front end? From the front? Sus?

### ISSUE THREAD

**Issue by wrighted** [music-retrieval/guitar-assistant#3]
We need a front end to this application.

Running options:

- Some random Python library,
- JavaScript tied in,
- Something else entirely.

I'm open to suggestion.

**Comment by alyssa-blair** [comment]
I propose we use Django for the general framework but we could use JavaScript for some of the front-end logic. Probably will require some other front-end language for any GUI stuff though. 

Also sus.

**Comment by wrighted** [comment]
SGTM do it.
